# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r309zUd0elNAMWTvSMhJ6ctKrr9cWtw7
"""

#setups and imports

#untuk membaca pdf
import pandas as pd

#untuk kalman filter
import numpy as np
import matplotlib.pyplot as plt

#Yang harus disediakan oleh user
FILE_NAME = "/content/maju1.csv"

df = pd.read_csv(FILE_NAME)

#jalankan hanya jika ingin melihat 5 baris pertama
print(df.head())

import matplotlib.pyplot as plt

# 1. Tentukan pilihan anchor yang ingin ditampilkan
SELECTION = [1, 2, 3]

# 2. Membuat plot untuk setiap pilihan
for n in SELECTION:
    plt.figure(figsize=(10, 4))

    # Konstruksi nama kolom secara dinamis
    time_col = f'time'
    dist_col = f'd{n}'

    if time_col in df.columns and dist_col in df.columns:
        plt.plot(df[time_col], df[dist_col], marker='o', linestyle='-', label=f'Data {dist_col}')

        plt.xlabel(f'Waktu Update ({time_col})')
        plt.ylabel(f'Jarak ({dist_col})')
        plt.title(f'Grafik Jarak {dist_col} terhadap {time_col}')
        plt.legend()
        plt.grid(True)
        plt.show()
    else:
        print(f'Kolom {time_col} atau {dist_col} tidak ditemukan dalam DataFrame.')

import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# Kalman Filter Function (1 Dimensi)
# ==========================================

#GLOBAL_Q = 0.05
#GLOBAL_R = 2.5

#UNTUK DIEDIT OLEH USER
# q = 0,01 r = 10
GLOBAL_Q = 0.001
GLOBAL_R = 1

def apply_kalman_filter(measurements, Q=0.001, R=100):
    """
    Applies a 1D Kalman Filter to a series of measurements.

    Args:
        measurements (array-like): The observed data from the sensor.
        Q (float): Process Noise. Controls how much the model trusts its prediction.
                   Smaller Q means more trust in the prediction.
        R (float): Measurement Noise. Controls how much the model trusts the new measurement.
                   Smaller R means more trust in the measurement.

    Returns:
        list: The Kalman Filtered estimates.
    """
    if len(measurements) == 0:
        return []

    # Tebakan awal sistem
    x_estimasi = measurements[0]  # Kita mulai tebakan dari titik data pertama
    P = 1.0  # Tingkat keraguan awal kita (Error Covariance)

    hasil_kalman = []

    for z in measurements:
        # --- TAHAP 1: PREDIKSI ---
        x_prediksi = x_estimasi  # Model sederhana: tebak posisi tetap sama dengan sebelumnya
        P_prediksi = P + Q

        # --- TAHAP 2: KOREKSI (UPDATE) ---
        K = P_prediksi / (P_prediksi + R)  # Menghitung "Kalman Gain" (Bobot Kepercayaan)
        x_estimasi = x_prediksi + K * (z - x_prediksi)
        P = (1 - K) * P_prediksi  # Update tingkat keraguan untuk iterasi berikutnya

        hasil_kalman.append(x_estimasi)

    return hasil_kalman

# ==========================================
# Apply Kalman Filter to d1, d2, d3 and Visualize
# ==========================================

# List of distance columns to process
d_columns = ['d1', 'd2', 'd3']

for d_col in d_columns:
    if d_col in df.columns and 'time' in df.columns:
        # 1. Extract data
        waktu = df['time'].values
        pengukuran_uwb = df[d_col].values

        # 2. Apply Kalman Filter
        hasil_kalman = apply_kalman_filter(pengukuran_uwb, Q=GLOBAL_Q, R=GLOBAL_R)

        # 3. Simpan ke kolom baru di DataFrame (d1_kf, d2_kf, d3_kf)
        kf_col_name = f"{d_col}_kf"
        df[kf_col_name] = hasil_kalman
    else:
        print(f"Kolom '{d_col}' atau 'time' tidak ditemukan dalam DataFrame.")

# Menampilkan 5 baris pertama untuk memastikan kolom baru sudah ada
print("\nDataFrame dengan kolom Kalman Filter baru:")
print(df[['time', 'd1', 'd1_kf', 'd2', 'd2_kf', 'd3', 'd3_kf']].head())

#Jalankan kode berikut untuk menampilkan grafik dari d(n)_kf
for d_col in d_columns:
    if d_col in df.columns and 'time' in df.columns:
        kf_col_name = f"{d_col}_kf"
        # 4. VISUALISASI HASIL (MENGGUNAKAN DATA DARI DATAFRAME)
        plt.figure(figsize=(12, 6))
        plt.plot(df['time'], df[d_col], label=f'Data Sensor UWB ({d_col})', color='red', alpha=0.7, linewidth=1)
        plt.plot(df['time'], df[kf_col_name], label=f'Estimasi Kalman Filter ({kf_col_name})', color='blue', linewidth=2)

        plt.title(f'Kalman Filter 1D untuk Jarak {d_col}')
        plt.xlabel('Waktu (detik)')
        plt.ylabel('Jarak (Meter)')
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.show()
    else:
        print(f"Kolom '{d_col}' atau 'time' tidak ditemukan dalam DataFrame.")

def get_trilateration_2d(p1, p2, p3, d1, d2, d3):
    """
    Mencari posisi (x, y) menggunakan metode trilaterasi.

    Args:
        p1, p2, p3: Tuple/List (x, y) posisi masing-masing anchor.
        d1, d2, d3: Jarak (radius) dari masing-masing anchor.
    """
    x1, y1 = p1
    x2, y2 = p2
    x3, y3 = p3

    # Persamaan sistem linear dari perpotongan lingkaran
    A = 2*x2 - 2*x1
    B = 2*y2 - 2*y1
    C = d1**2 - d2**2 - x1**2 + x2**2 - y1**2 + y2**2
    D = 2*x3 - 2*x2
    E = 2*y3 - 2*y2
    F = d2**2 - d3**2 - x2**2 + x3**2 - y2**2 + y3**2

    # Menghitung titik x dan y menggunakan determinan
    denominator = (A*E - B*D)
    if abs(denominator) < 1e-9:
        return None # Anchor sejajar, tidak bisa dihitung

    x = (C*E - F*B) / denominator
    y = (A*F - D*C) / denominator

    return x, y

# --- Tentukan Posisi Anchor Anda di sini ---
# Contoh: Anchor diletakkan di sudut ruangan
ANCHOR1 = (5.92, 5.02)
ANCHOR2 = (0, 0)
ANCHOR3 = (10.58, 0)

# Contoh pemanggilan menggunakan data dari baris pertama DataFrame
# test_pos = get_trilateration_2d(ANCHOR1, ANCHOR2, ANCHOR3, df['d1'][0], df['d2'][0], df['d3'][0])
# print(f"Estimasi posisi awal: {test_pos}")

df['x'], df['y'] = get_trilateration_2d(
    ANCHOR1, ANCHOR2, ANCHOR3,
    df['d1'], df['d2'], df['d3']
)
df['x_kf'], df['y_kf'] = get_trilateration_2d(
    ANCHOR1, ANCHOR2, ANCHOR3,
    df['d1_kf'], df['d2_kf'], df['d3_kf']
)
print(df[['time', 'x', 'y','x_kf', 'y_kf']].head())

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))

# Plot raw trilateration data
plt.scatter(df['x'], df['y'], color='red', alpha=0.3, s=10, label='Raw UWB (x, y)')

# Plot Kalman Filtered data
plt.scatter(df['x_kf'], df['y_kf'], color='blue', alpha=0.6, s=10, label='Kalman Filtered (x_kf, y_kf)')

# Plot Anchor positions
anchors_x = [ANCHOR1[0], ANCHOR2[0], ANCHOR3[0]]
anchors_y = [ANCHOR1[1], ANCHOR2[1], ANCHOR3[1]]
plt.scatter(anchors_x, anchors_y, color='black', marker='^', s=100, label='Anchors')

# Add labels to anchors
for i, (ax, ay) in enumerate(zip(anchors_x, anchors_y)):
    plt.text(ax, ay, f' Anchor {i+1}', verticalalignment='bottom')

plt.title('Scatter Plot: Raw vs Kalman Filtered Positioning')
plt.xlabel('X Coordinate (m)')
plt.ylabel('Y Coordinate (m)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.axis('equal')
plt.show()

# 1. Pilih kolom yang ingin disimpan
# Anda bisa menyertakan 'time' agar data koordinat memiliki referensi waktu
df_output = df[['time', 'x', 'y', 'x_kf', 'y_kf']]

# 2. Simpan ke file CSV
# index=False digunakan agar nomor baris tidak ikut tersimpan sebagai kolom baru
df_output.to_csv('hasil_lokalisasi_lurus.csv', index=False)

print("Data berhasil diekstrak ke 'hasil_lokalisasi_jolie.csv'")